spring:
  jersey.application-path: phonebook
  application:
    name: Phonebook-Api
server:
  port: 2019
  address: 0.0.0.0
  use-forward-headers: true
  jsp-servlet.registered: false
hibernate:
  show_sql: false
  dialect: org.hibernate.dialect.MySQL5Dialect
  hbm2ddl:
    auto: none
flyway:
  baseline-on-migrate: true
  baseline-description: Phonebook
  baseline-version: 1
security:
  sessions: stateless
  basic.enabled: true
  user:
    name: manage
    password: letmein
auth:
  admin:
    username: admin
    password: admin
  reader:
    username: reader
    password: reader